### ISSUE TITLE
8.3.3 required minimum node version

### ISSUE THREAD

**Issue by amneacsu** [redux-form/redux-form#4656]
### Subject of the issue

`redux-form@8.3.3` fails to install through `yarn` if using a node version prior to 12.16.1.

### Your environment

- **OS**: macOS 10.15.4
- **Packages**: redux-form@8.3.3
- **Env**: node 12.10.0. npm 6.13.4, yarn 1.22.4

### Steps to reproduce

1. `nvm use 12.10`
2. `yarn init`
3. `yarn add redux-form@8.3.3`

I've uploaded a reproduction at https://github.com/amneacsu/redux-form-833 but it's literally just a brand new `package.json`.

### Expected behaviour

`redux-form` installs successfully.

### Actual behaviour

I get an error from `yarn` and it refuses to install: `error redux-form@8.3.3: The engine "node" is incompatible with this module. Expected version ">=12.16.1". Got "12.10.0"`

### Other information

`npm` will happily install without the error.

**Comment by DonovanCharpin** [comment]
I have the exact same issue on my side, got node 10.13 though.

**Comment by PeledYuval** [comment]
This issue still exists when installing with yarn. This seems like an easy fix, removing the "engines" part from the package.json. Can this please be prioritized?

**Comment by iamandrewluca** [comment]
Fixed in https://github.com/redux-form/redux-form/releases/tag/v8.3.4

**Comment by PeledYuval** [comment]
@iamandrewluca 
Hi Andrew,

Thanks for the quick revert, is it possible to ask to return it to the value it was before?
[This commit](https://github.com/redux-form/redux-form/commit/fee51ec94cb4c62a0b4c6c0ffee377733c324b88#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) changed it from 8.10 to 12 and your [your revert](https://github.com/redux-form/redux-form/commit/04d2e9307be7e1f1956ddd325f94d5574af2ec37) changed it to 8.17.0

Is it possible to change it to 8.10? We have a project that runs on Node 8.15 (I know, we're working on changing it) and client builds are failing due to this. Thank you very much!

**Comment by iamandrewluca** [comment]
Done.

**Comment by PeledYuval** [comment]
Thanks a lot! Appreciate it.
