### ISSUE TITLE
Wizard Form with FieldArray

### ISSUE THREAD

**Issue by ppb1984** [redux-form/redux-form#4663]
Hi,

I am having `WizardForm` in `FieldArray`. When user click on `ADD` then `WizardForm` is added to screen.

My Problem is, suppose I have three  `WizardForm` on my screen and if I click on `NEXT` or `PREVIOUS` button from any of the form then all form is moved according to action.

I am not sure how can I use state for  `WizardForm` so every form can behave separately.

**Comment by iamandrewluca** [comment]
@ppb1984 each form has to have it's unique name, when using the `redux-form`

e.g.

```js
const YourForm = reduxForm({})(FormComponent)

function App() {
  const [formNumber, setFormNumber] = React.useState(1)

  return (
    <React.Fragment>
      <YourForm name={`form-${formNumber}`} />
      <button onClick={() => setFormNumber(formNUmber + 1)}>NEXT</button>
    </React.Fragment>
  )
}

```

I'll close this because it is a question. 

Please ask and answer questions on [Gitter][gitter] or [Spectrum][spectrum].
Or you can search or ask questions on [StackOverflow][stackoverflow] with redux-form tag

[spectrum]: https://spectrum.chat/redux-form
[gitter]: https://gitter.im/erikras/redux-form
[stackoverflow]: https://stackoverflow.com/questions/tagged/redux-form
